#!/bin/sh
# Does the wrist actually decode what the phone actually sends?
#
# core's watchFeed() writes the JSON; WatchStore.swift's Codable structs read
# it. Nothing checked that they agree, and that seam is exactly where the bug
# Sean spent a week on lived: the feed sent an EMPTY folder list (a folder
# with no `app` field failed a strict comparison), the watch decoded it
# perfectly, and drew one flat ungrouped page. Every test on both sides was
# green — because each side was tested against its own idea of the shape.
#
# So this runs BOTH real implementations against each other. The fixture is
# generated by the real watchFeed from real record shapes, and decoded by the
# real structs pulled out of WatchStore.swift. Nothing is re-typed here: if
# either side changes, this runs the change.
#
#   sh tools/check-watch-feed.sh
set -e
cd "$(dirname "$0")/.."

TMP=$(mktemp -d -t watchfeed)
trap 'rm -rf "$TMP"' EXIT

# 1. The phone's side: the real feed, from an account whose folders predate the
#    `app` field — which is what Sean's oldest folders are, and the case that
#    was silently dropped.
cat > "$TMP/feed.mjs" <<'JS'
import { watchFeed } from '__CORE__';
const f = (id, name, ord, app) => ({ id, type: 'folder', updated: 1, payload: { name, color: '#123456', ord, ...(app ? { app } : {}) } });
const s = (id, name, folderId, ord) => ({ id, type: 'section', updated: 1, payload: { name, folderId, ord } });
const r = (id, text, folderId, sectionId, due = null, time = null) => ({
  id, type: 'reminder', updated: 1,
  payload: { text, due, time, done: false, repeat: null, folderId, sectionId, indent: 0, ord: id },
});
const recs = [
  f('f1', 'Home', 'a'),              // NO app — the milestone-1 shape
  f('f2', 'Work', 'b', 'reminders'), // the current shape
  f('n1', 'Recipes', 'c', 'notes'),  // must not travel
  s('s1', 'Now', 'f1', 'a'),
  s('s2', 'Later', 'f1', 'b'),
  s('s3', 'Desk', 'f2', 'a'),
  r('r1', 'bins', 'f1', 's1', '2026-08-09', '15:00'),
  r('r2', 'lightbulb', 'f1', 's2'),
  r('r3', 'invoice', 'f2', 's3'),
  r('r4', 'orphan', 'f9', 's9'),     // a folder that never arrived
  { id: 'c1', type: 'calendar', updated: 1, payload: { name: 'Personal', color: '#60a5fa', ord: 'a' } },
  { id: 'e1', type: 'event', updated: 1, payload: { text: 'Chase', date: '2026-08-09', time: '17:00', repeat: null, calendarId: 'c1', ord: 'a' } },
];
process.stdout.write(JSON.stringify(watchFeed(recs, '2026-08-09')));
JS
# The generated script lives in a temp dir, so a relative import would
# resolve against /tmp. Absolute, from the repo root this script cd-ed to.
sed -i '' "s#__CORE__#$PWD/packages/core/src/watch.ts#" "$TMP/feed.mjs"
npx tsx "$TMP/feed.mjs" > "$TMP/feed.json" 2>/dev/null \
  || npx --yes tsx "$TMP/feed.mjs" > "$TMP/feed.json"
[ -s "$TMP/feed.json" ] || { echo "the feed fixture came out empty" >&2; exit 1; }

# 2. The wrist's side: the real structs, and the real List shape out of
#    decode(), lifted rather than retyped.
python3 - "$TMP/decode.swift" "$TMP/feed.json" <<'PY'
import sys, re
src = open('apps/app/targets/watch/WatchStore.swift').read()

def grab_type(name):
    i = src.index('struct %s' % name)
    depth, k = 0, src.index('{', i)
    while True:
        if src[k] == '{': depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0: break
        k += 1
    return src[i:k+1]

types = '\n'.join(grab_type(n) for n in
                  ['WatchItem', 'WatchFolder', 'WatchSection', 'WatchGroup', 'WatchEvent'])
# The List that decode() actually uses, indentation and all.
inner = grab_type('List')

# The wrist's ONE piece of its own logic: the fallback that draws a flat list
# when the payload carries no groups. It is static and pure precisely so this
# can call it; as a computed property over `store` it could only ever run
# inside a rendered view on a watch.
view = open('apps/app/targets/watch/ReminderListView.swift').read()
i = view.index('static func drawnGroups(')
depth, k = 0, view.index('{', i)
while True:
    if view[k] == '{': depth += 1
    elif view[k] == '}':
        depth -= 1
        if depth == 0: break
    k += 1
fallback = view[i:k+1].replace('static func', 'func')

open(sys.argv[1], 'w').write('''
import Foundation
%s
%s
let data = try Data(contentsOf: URL(fileURLWithPath: "%s"))
let list = try JSONDecoder().decode(List.self, from: data)

var bad = 0
func check(_ ok: Bool, _ what: String) { if !ok { print("  x " + what); bad += 1 } }

// The bug, stated as a test: a folder whose record carries no `app` is a
// reminders folder, so it MUST arrive.
let folderNames = (list.folders ?? []).map { $0.name }
check(folderNames == ["Home", "Work"], "folders should be [Home, Work], got \\(folderNames)")

// …and the wrist must receive it already GROUPED, not flat.
let groups = list.groups ?? []
check(groups.count == 3, "expected 3 groups (Home, Work, strays), got \\(groups.count)")
check(groups.first?.folderName == "Home", "first group is Home, got \\(String(describing: groups.first?.folderName))")

// Two sections under Home, so both are named; one under Work, so it is not.
let homeSections = groups.first?.sections.map { $0.sectionName } ?? []
check(homeSections == ["Now", "Later"], "Home names both its sections, got \\(homeSections)")
if groups.count > 1 {
    let workSections = groups[1].sections.map { $0.sectionName }
    check(workSections == [nil], "a folder with ONE section has already been named, got \\(workSections)")
}
// A row whose folder never arrived is still reachable — losing a reminder to
// a missing header is the worst trade on a 41mm screen.
if groups.count > 2 {
    let strayTexts = groups[2].sections.flatMap { $0.items.map { $0.text } }
    check(groups[2].folderName == nil, "the stray group draws no header")
    check(strayTexts == ["orphan"], "the orphan is still shown, got \\(strayTexts)")
}

// The rest of the envelope the wrist reads.
check(list.items.count == 4, "4 open reminders, got \\(list.items.count)")
check(list.items.allSatisfy { $0.folderId != nil }, "every row carries its folderId")
check((list.sections ?? []).count == 3, "3 sections travel, got \\((list.sections ?? []).count)")
check((list.events ?? []).count == 1, "1 event travels, got \\((list.events ?? []).count)")
check((list.events ?? []).first?.color == "#60a5fa", "an event carries its calendar's colour")

// The fallback, both branches. It is what kept Sean's watch usable while the
// feed was sending no groups at all: an OLD cache decodes with items and no
// groups, and drawing groups then produced a completely BLANK page — not even
// the empty state, because items was not empty.
let flat = drawnGroups(groups: [], items: list.items)
check(flat.count == 1, "no groups -> exactly one flat group, got \\(flat.count)")
check(flat.first?.folderName == nil, "the flat fallback draws no header")
check(flat.first?.sections.first?.items.count == list.items.count,
      "the flat fallback shows every row, got \\(String(describing: flat.first?.sections.first?.items.count))")
// …and when there ARE groups it must not second-guess them.
let kept = drawnGroups(groups: groups, items: list.items)
check(kept.count == groups.count, "with groups present the fallback passes them through")

print(bad == 0
      ? "watch feed: the phone's JSON and the wrist's decoder agree"
      : "watch feed: \\(bad) MISMATCHES")
exit(bad == 0 ? 0 : 1)
''' % (types + '\n' + fallback, inner.replace('        ', ''), sys.argv[2]))
PY

swift "$TMP/decode.swift"
