#!/bin/sh
# Does the wrist actually decode what the phone actually sends?
#
# core's watchFeed() writes the JSON; WatchStore.swift's Codable structs read
# it. Nothing checked that they agree, and that seam is exactly where the bug
# Sean spent a week on lived: the feed sent an EMPTY folder list (a folder
# with no `app` field failed a strict comparison), the watch decoded it
# perfectly, and drew one flat ungrouped page. Every test on both sides was
# green — because each side was tested against its own idea of the shape.
#
# So this runs BOTH real implementations against each other. The fixture is
# generated by the real watchFeed from real record shapes, and decoded by the
# real structs pulled out of WatchStore.swift. Nothing is re-typed here: if
# either side changes, this runs the change.
#
#   sh tools/check-watch-feed.sh
set -e
cd "$(dirname "$0")/.."

TMP=$(mktemp -d -t watchfeed)
trap 'rm -rf "$TMP"' EXIT

# 1. The phone's side: the real feed, from an account whose folders predate the
#    `app` field — which is what Sean's oldest folders are, and the case that
#    was silently dropped.
cat > "$TMP/feed.mjs" <<'JS'
import { watchFeed } from '__CORE__';
const f = (id, name, ord, app) => ({ id, type: 'folder', updated: 1, payload: { name, color: '#123456', ord, ...(app ? { app } : {}) } });
const s = (id, name, folderId, ord) => ({ id, type: 'section', updated: 1, payload: { name, folderId, ord } });
const r = (id, text, folderId, sectionId, due = null, time = null) => ({
  id, type: 'reminder', updated: 1,
  payload: { text, due, time, done: false, repeat: null, folderId, sectionId, indent: 0, ord: id },
});
const recs = [
  f('f1', 'Home', 'a'),              // NO app — the milestone-1 shape
  f('f2', 'Work', 'b', 'reminders'), // the current shape
  f('n1', 'Recipes', 'c', 'notes'),  // must not travel
  s('s1', 'Now', 'f1', 'a'),
  s('s2', 'Later', 'f1', 'b'),
  s('s3', 'Desk', 'f2', 'a'),
  r('r1', 'bins', 'f1', 's1', '2026-08-09', '15:00'),
  r('r2', 'lightbulb', 'f1', 's2'),
  r('r3', 'invoice', 'f2', 's3'),
  r('r4', 'orphan', 'f9', 's9'),     // a folder that never arrived
  { id: 'c1', type: 'calendar', updated: 1, payload: { name: 'Personal', color: '#60a5fa', ord: 'a' } },
  { id: 'e1', type: 'event', updated: 1, payload: { text: 'Chase', date: '2026-08-09', time: '17:00', repeat: null, calendarId: 'c1', ord: 'a' } },
  // A SECOND calendar, and an event on it on a day of its own. Without both,
  // a calendar selection has nothing to exclude and nothing to empty, so the
  // mirror checks below would pass whatever the filter did.
  { id: 'c2', type: 'calendar', updated: 1, payload: { name: 'Work', color: '#ff00aa', ord: 'b' } },
  { id: 'e2', type: 'event', updated: 1, payload: { text: 'Standup', date: '2026-08-11', time: '09:00', repeat: null, calendarId: 'c2', ord: 'a' } },
];
// The last argument is the widget's own calendar selection, which the phone
// reads out of the App Group and the WATCH applies — Sean's "watch should
// mirror folders selected by widget".
process.stdout.write(JSON.stringify(watchFeed(recs, '2026-08-09', null, ['c1'])));
JS
# The generated script lives in a temp dir, so a relative import would
# resolve against /tmp. Absolute, from the repo root this script cd-ed to.
sed -i '' "s#__CORE__#$PWD/packages/core/src/watch.ts#" "$TMP/feed.mjs"
npx tsx "$TMP/feed.mjs" > "$TMP/feed.json" 2>/dev/null \
  || npx --yes tsx "$TMP/feed.mjs" > "$TMP/feed.json"
[ -s "$TMP/feed.json" ] || { echo "the feed fixture came out empty" >&2; exit 1; }

# 2. The wrist's side: the real structs, and the real List shape out of
#    decode(), lifted rather than retyped.
python3 - "$TMP/decode.swift" "$TMP/feed.json" <<'PY'
import sys, re
src = open('apps/app/targets/watch/WatchStore.swift').read()

def grab_type(name):
    i = src.index('struct %s' % name)
    depth, k = 0, src.index('{', i)
    while True:
        if src[k] == '{': depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0: break
        k += 1
    return src[i:k+1]

types = '\n'.join(grab_type(n) for n in
                  ['WatchItem', 'WatchFolder', 'WatchSection', 'WatchGroup', 'WatchEvent', 'WatchDay', 'WatchLine'])
# The List that decode() actually uses, indentation and all.
inner = grab_type('List')

# The wrist's ONE piece of its own logic: the fallback that draws a flat list
# when the payload carries no groups. It is static and pure precisely so this
# can call it; as a computed property over `store` it could only ever run
# inside a rendered view on a watch.
view = open('apps/app/targets/watch/ReminderListView.swift').read()
i = view.index('static func drawnGroups(')
depth, k = 0, view.index('{', i)
while True:
    if view[k] == '{': depth += 1
    elif view[k] == '}':
        depth -= 1
        if depth == 0: break
    k += 1
fallback = view[i:k+1].replace('static func', 'func')

# The wrist's copy of the WIDGET's filter. It is a deliberate second copy of
# HomeWidget.swift's drawnDays rule — two targets, two binaries, neither able
# to import the other — so something has to run it against a real core feed.
# Same arrangement as the two clock formatters.
tabs = open('apps/app/targets/watch/WatchTabs.swift').read()
i = tabs.index('static func drawnWidgetDays(')
depth, k = 0, tabs.index('{', i)
while True:
    if tabs[k] == '{': depth += 1
    elif tabs[k] == '}':
        depth -= 1
        if depth == 0: break
    k += 1
fallback += '\n' + tabs[i:k+1].replace('static func', 'func')

# …and the total-item cap beside it. Two nested caps (four days, six lines
# each) used to hide anything past the fourth day, which is exactly how Sean's
# shared events showed on the widget and not on the wrist.
j = tabs.index('static func capped(')
depth, k2 = 0, tabs.index('{', j)
while True:
    if tabs[k2] == '{': depth += 1
    elif tabs[k2] == '}':
        depth -= 1
        if depth == 0: break
    k2 += 1
import re as _re
_lim = _re.search(r'static let PAGE_LIMIT = (\d+)', tabs)
if not _lim:
    print('WatchTabs has no PAGE_LIMIT — the first page has no stated cap'); raise SystemExit(1)
fallback += '\nlet PAGE_LIMIT = ' + _lim.group(1) + '\n'
fallback += tabs[j:k2+1].replace('static func', 'func').replace('limit: Int = PAGE_LIMIT', 'limit: Int')

open(sys.argv[1], 'w').write('''
import Foundation
%s
%s
let data = try Data(contentsOf: URL(fileURLWithPath: "%s"))
let list = try JSONDecoder().decode(List.self, from: data)

var bad = 0
func check(_ ok: Bool, _ what: String) { if !ok { print("  x " + what); bad += 1 } }

// The bug, stated as a test: a folder whose record carries no `app` is a
// reminders folder, so it MUST arrive.
let folderNames = (list.folders ?? []).map { $0.name }
check(folderNames == ["Home", "Work"], "folders should be [Home, Work], got \\(folderNames)")

// …and the wrist must receive it already GROUPED, not flat.
let groups = list.groups ?? []
check(groups.count == 3, "expected 3 groups (Home, Work, strays), got \\(groups.count)")
check(groups.first?.folderName == "Home", "first group is Home, got \\(String(describing: groups.first?.folderName))")

// Two sections under Home, so both are named; one under Work, so it is not.
let homeSections = groups.first?.sections.map { $0.sectionName } ?? []
check(homeSections == ["Now", "Later"], "Home names both its sections, got \\(homeSections)")
// Written so a SHORT list fails here too, rather than skipping quietly: a
// check that did not run reads exactly like one that passed.
let workSections = groups.count > 1 ? groups[1].sections.map { $0.sectionName } : []
check(workSections == [nil], "a folder with ONE section has already been named, got \\(workSections)")
// A row whose folder never arrived is still reachable — losing a reminder to
// a missing header is the worst trade on a 41mm screen.
let strayTexts = groups.count > 2 ? groups[2].sections.flatMap { $0.items.map { $0.text } } : []
check(groups.count > 2 && groups[2].folderName == nil, "the stray group draws no header")
check(strayTexts == ["orphan"], "the orphan is still shown, got \\(strayTexts)")

// The rest of the envelope the wrist reads.
check(list.items.count == 4, "4 open reminders, got \\(list.items.count)")
check(list.items.allSatisfy { $0.folderId != nil }, "every row carries its folderId")
check((list.sections ?? []).count == 3, "3 sections travel, got \\((list.sections ?? []).count)")
check((list.events ?? []).count == 2, "2 events travel, got \\((list.events ?? []).count)")
check((list.events ?? []).first?.color == "#60a5fa", "an event carries its calendar's colour")

// The fallback, both branches. It is what kept Sean's watch usable while the
// feed was sending no groups at all: an OLD cache decodes with items and no
// groups, and drawing groups then produced a completely BLANK page — not even
// the empty state, because items was not empty.
let flat = drawnGroups(groups: [], items: list.items)
check(flat.count == 1, "no groups -> exactly one flat group, got \\(flat.count)")
check(flat.first?.folderName == nil, "the flat fallback draws no header")
check(flat.first?.sections.first?.items.count == list.items.count,
      "the flat fallback shows every row, got \\(String(describing: flat.first?.sections.first?.items.count))")
// …and when there ARE groups it must not second-guess them.
let kept = drawnGroups(groups: groups, items: list.items)
check(kept.count == groups.count, "with groups present the fallback passes them through")

// The first page mirrors the home-screen widget: the same `days` core built
// for it, filtered by the same calendar selection. Sean asked for both, and
// the two halves fail independently below.
let days = list.days ?? []
check(!days.isEmpty, "the wrist is given the widget's days at all — the page draws nothing without them")
check(list.widgetCalendars == ["c1"], "the widget's selection reaches the wrist, got \(String(describing: list.widgetCalendars))")

// Unfiltered, both events are there. This is the precondition: without it the
// filter check below could pass by the event never having arrived.
let allIds = drawnWidgetDays(days: days, wanted: []).flatMap { $0.lines.map { $0.id } }
check(allIds.contains("e1") && allIds.contains("e2"),
      "with NO selection every event is drawn — an empty picker is not an empty page, got \(allIds)")

let mine = drawnWidgetDays(days: days, wanted: ["c1"])
let mineIds = mine.flatMap { $0.lines.map { $0.id } }
check(mineIds.contains("e1"), "the picked calendar's event stays, got \(mineIds)")
check(!mineIds.contains("e2"), "an event on an UNPICKED calendar goes, got \(mineIds)")
// The half that makes this different from the calendar picker: a reminder is
// never filtered here, because the tri-state already decided it.
check(mineIds.contains("r1"), "a REMINDER survives a calendar selection, got \(mineIds)")
// Stated as a SET comparison rather than by naming rows. The first draft
// asserted r2 was there too and was simply wrong — r2 is undated, and an
// undated reminder only rides onto today when its folder's tri-state is
// 'all', which this fixture does not set. Naming rows meant asserting my
// guess about the tri-state; comparing the sets asserts the actual rule,
// which is that a CALENDAR selection changes no reminder at all.
let remsAll = Set(drawnWidgetDays(days: days, wanted: []).flatMap { $0.lines.filter { $0.isReminder }.map { $0.id } })
let remsPicked = Set(mine.flatMap { $0.lines.filter { $0.isReminder }.map { $0.id } })
check(!remsAll.isEmpty, "there must be reminders in the mirror at all, or the comparison below is vacuous")
check(remsAll == remsPicked, "a calendar selection changes NO reminder — \(remsAll) became \(remsPicked)")
// e2 was alone on its day, so that day must vanish rather than draw a bare heading.
let soloDay = drawnWidgetDays(days: days, wanted: []).first { $0.lines.contains { $0.id == "e2" } }
check(soloDay?.lines.count == 1, "the fixture needs a day whose ONLY line is e2, or the next check cannot fail")
let unfilteredCount = drawnWidgetDays(days: days, wanted: []).count
check(mine.count == unfilteredCount - 1,
      "the emptied day disappears, not drawn headless — \(unfilteredCount) days became \(mine.count)")
check(mine.allSatisfy { !$0.lines.isEmpty }, "no day is ever drawn with an empty line list")

// Sean, 2026-08-11: "first tab should have up to 10 reminders/events from the
// future total (but from the same sources as the widget)". It was the first
// FOUR days with six lines each, and those two caps multiply: an event on day
// five was unreachable however empty days one to four were. That is why his
// shared events were on the widget and missing from the wrist.
let manyDays = (0..<9).map { d in
    WatchDay(date: "2026-08-\(11 + d)",
             lines: (0..<3).map { i in
                 WatchLine(id: "d\(d)-\(i)", text: "x", time: nil, isReminder: true, overdue: false, color: nil, calendarId: nil)
             })
}
let page = capped(manyDays, limit: PAGE_LIMIT)
let shown = page.flatMap { $0.lines }
check(shown.count == PAGE_LIMIT, "the first page shows PAGE_LIMIT items in total — got \(shown.count)")
// Counted ACROSS days, not within them: 10 items at 3 a day has to reach the
// fourth day. The old shape stopped at four days and six lines and could not.
check(page.count == 4, "…drawn from as many days as it takes — got \(page.count)")
check(page.last?.lines.count == 1, "…with the last day part-drawn, since the cap is items not days — got \(page.last?.lines.count ?? -1)")
// Order is preserved and nothing is invented.
check(shown.map { $0.id } == manyDays.flatMap { $0.lines }.prefix(PAGE_LIMIT).map { $0.id },
      "the page is the first PAGE_LIMIT items in feed order")
// An event beyond the old four-day window now reaches the wrist. This is the
// regression itself, stated so it cannot come back.
let deepId = manyDays[4].lines[0].id
let reach = capped(manyDays, limit: 15).flatMap { $0.lines }.map { $0.id }
check(reach.contains(deepId), "an item on the fifth day is reachable — the four-day window is gone")
// Fewer items than the cap draws them all, so the cap is a ceiling not a quota.
check(capped(Array(manyDays.prefix(2)), limit: PAGE_LIMIT).flatMap { $0.lines }.count == 6,
      "a short list draws in full")

print(bad == 0
      ? "watch feed: the phone's JSON and the wrist's decoder agree"
      : "watch feed: \\(bad) MISMATCHES")
exit(bad == 0 ? 0 : 1)
''' % (types + '\n' + fallback, inner.replace('        ', ''), sys.argv[2]))
PY

swift "$TMP/decode.swift"
